slub/slub_digitalcollections

- Configuration/TypoScript/Plugin/Kitodo/common.typoscript
- Resources/Private/Partials/KitodoPageView.html
- Resources/Private/Plugins/Kitodo/Pageview.html
Search in fulltext with the search plugin does not make sense, if we have no fulltext to search in.
This may be interessting to search in metadata. But do we want this?
> Do not add search option if no fulltext search is available

- Resources/Private/Language/de.locallang_kitodo.xlf
- Resources/Private/Language/locallang_kitodo.xlf
The metadata record "terms of use" may be used twice to link each entry separately. Don't ask ;-)
> Add double localtermsofuse2 label

- Resources/Private/Plugins/Kitodo/Templates/Toolbox/Main.html
- Currently, in the Fluid template it is assumed that there is at least a link to a single PDF download. This isn't always the case, so a non-functioning link is rendered, and the menu isn't properly disabled when no link exists. So this PR adds a check.
- Also, each download link is rendered into an individual `<li>` element to reproduce previous markup more closely.
> Fix display and conditions of PDF download link

- Resources/Private/Plugins/Kitodo/Templates/Toolbox/Main.html
Depends on https://github.com/kitodo/kitodo-presentation/pull/941
Probably it should be optimized even further (e.g.removing window for misspelling).
Idea: The 'tool' setting should be removed and the name of the tool should be derived from the plugin name.
It is necessary for fixing issue https://github.com/kitodo/kitodo-presentation/issues/994
> Rename conditions for tool rendering to match Kitodo.Presentation

- ext_localconf.php
Error:
`[NOTICE] request="7f793c25ff4d7" component="TYPO3.CMS.deprecations": Calling method TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin with argument $extensionName ("Slub.SlubDigitalcollections") containing the vendor name ("Slub") is deprecated and will stop working in TYPO3 11.0. - {"file":"/var/www/html/public/typo3/sysext/extbase/Classes/Utility/ExtensionUtility.php","line":171}`
Since TYPO3 10 `$extensionName` should be called only as 'SlubDigitalcollections'. This change is needed for upgrade to TYPO3 11, but it will not work with TYPO3 9.
Source: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Deprecation-87550-UseControllerClassesWhenRegisteringPluginsmodules.html
> Fix call to`ExtensionUtility::configurePlugin`

- .github/workflows/npm-grunt.yml
This PR adds a GH workflow to check whether the compiled files are up to date with their sources.
It can easily happen that we commit code without grunt running, or merge a PR that is not up to date with master. This GH workflow causes the test to fail in such a case and you can do it afterwards.
> Grunt action to verify if compiled files are up to date

- Resources/Private/Plugins/Kitodo/Templates/Toolbox/Main.html
Currently, the same icons are used for downloads of individual pages as well as entire publications, although there is actually a differentiation. This PR sets the correct class so the differentiation can take place.
> Fix wrong page download icon

- Classes/ViewHelpers/PageInfoViewHelper.php
Change the path of `PageRepository` from `TYPO3\CMS\Frontend\Page\PageRepository` to `TYPO3\CMS\Core\Domain\Repository\PageRepository`.
See here: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Deprecation-88746-PageRepositoryPHPClassMovedFromFrontendToCoreExtension.html
> In previous TYPO3 versions, accessing records was mixed between Frontend (handled by PageRepository) and Backend (handled by static methods in BackendUtility). In TYPO3 v9, the Context API was introduced and PageRepository now acts as a strong database accessor which is not bound to Frontend anymore, at all.
>
>In addition, various places of the backend also used PageRepository already, which violated the separation of packages, as TYPO3 Core aims to strictly separate Frontend and Backend application …
> Fix Deprecation: #88746 Path to `PageRepository`

- .github/phpstan.neon
`DocumentRepository::findSolrByCollections` is available in Kitodo 4.1, but this repository still uses 4.0 - this is going to be changed soon
Should be merged before other PRs
> Adjust PHPStan

- composer.json
- ext_emconf.php
update composer for typo3 require max version ^11.5
necessary for seamless install of `slub/ddev-dfgviewer-dist`
> composer update in compatibility with typo3 v11.5

- ext_localconf.php
Fix for errors:
```
Uncaught TYPO3 Exception #1476107295: PHP Warning: Undefined array key "slub_digitalcollections_matomo_collections" in /var/www/extensions/slub_digitalcollections/ext_localconf.php line 19
thrown in file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php
in line 137
```
```
Uncaught TYPO3 Exception #1476107295: PHP Warning: Undefined array key "slub_digitalcollections_collections" in /var/www/extensions/slub_digitalcollections/ext_localconf.php line 30
thrown in file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php
in line 137
```
> Fix cache assignment in `ext_localconf.php for arrays

- Configuration/TCA/Overrides/tt_content.php
The first parameter $extensionName of method \TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin used to contain the vendor name in the past.
As the vendor name does not have any effect at all, it's usage has been marked as deprecated.
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.1/Deprecation-88995-CallingRegisterPluginWithVendorName.html
> Fix calling registerPlugin with vendor name

- Resources/Private/Plugins/Kitodo/Templates/Toolbox/Main.html
Currently, the model download tool exists in Kitodo.Presentation.
https://github.com/kitodo/kitodo-presentation/blob/f088772a644aa1af16a5b6d8fc57c6f621514430/Resources/Private/Templates/Toolbox/Main.html#L78-L88
In DFG-Viewer, the model download tool will not be displayed because the toolbox file of Digital Collections is used.
It's a bug in DFG-Viewer.
> [FEATURE] Add model download tool

- Resources/Private/Plugins/SingleCollection/Partials/Pagination.html
Should be used signs `<` and `>` instead of long text which causes line to break
The same adjustment is made for original template in https://github.com/kitodo/kitodo-presentation/pull/1498
> [BUGFIX] Fix display for pagination - 4.0

- Resources/Private/Plugins/Kitodo/Partials/ListView/Results.html
- Resources/Private/Plugins/SingleCollection/Partials/Results.html
Link should only be attached to title instead of the whole result element.
> [BUGFIX] Restore displaying results to previous layout

- Resources/Private/Plugins/Kitodo/Templates/Collection/List.html
If title of collection is not in the same line as the link tag than it adds empty space before and after title. The ordering doesn't work as it takes first character which in this case is white space.
> [BUGFIX] Fix template for displaying list of collections - 4.0

- Resources/Private/Plugins/Kitodo/Partials/ListView/Results.html
- Resources/Private/Plugins/SingleCollection/Partials/Results.html
Several single quotes require escape characters.
Fixes: ed2c25180b53 ("Display [no title] for documents without title")
> Fix display of search results

- Configuration/TypoScript/Plugin/Kitodo/common.typoscript
fixing undefined "backend_layout" key Errors in several TYPO3 v12 BE Modules
see Screenshot:
> [BUGFIX] change the backend_layout check to use the traverse function

- Configuration/TypoScript/Plugin/Kitodo/common.typoscript
FIX Error in TYPO3 v12 while Indexing: 
```
[ RuntimeException ]                                             
Unable to call method "getQueryParams" of non-object "request".
```
> [BUGFIX] - Add support for Typo3 v12 - check for request object first

- Configuration/TypoScript/Plugin/Kitodo/setup.typoscript
adapted from DFG-Viewer, see:
https://github.com/slub/dfg-viewer/commit/fad5720327489a714bb695ed700c09e1537bd752
Kitodo.Presentation throws an error if this configuration key in the settings is missing.
`PHP Warning: Undefined array key "multiViewType" in /var/www/html/packages/kitodo-presentation/Classes/Controller/PageViewController.php line 466`
@beatrycze-volk, should the check for a existing `multiViewType` Key should also be added to Kitodo?
Then we have to add the check here:
https://github.com/kitodo/kitodo-presentation/commit/fb1a41718815c916eeb40599a04b119e1b38265c
> Add multiViewType to `tx_dlf_pageview` in Kitodo config adapted from DFG-Viewer

- Classes/ViewHelpers/PageInfoViewHelper.php
As access to `$GLOBALS['TSFE']` directly is [strongly discouraged](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/TSFE/Index.html#accessing-tsfe) and Deprecated since version 13.4, we switch to a modern approach.
See advice in TYPO3 reference coreapi documentation:
https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/TSFE/Index.html#tsfe-pageid
We get the PSR-7 request object, triaged by TYPO3 Version Check for >=11.3:
https://docs.typo3.org/permalink/t3coreapi:getting-typo3-request-object
PHPStan Error is Ignored, as written in the link above:
> In a ViewHelper you can get the rendering request from the rendering context. For this you have to rely on the fact that a \TYPO3\CMS\Fluid\Core\Rendering\RenderingContext is passed to the ViewHelpers …
> Fix PageInfoViewHelper to retrieve page UID from routing context
