slub/slub_digitalcollections

- Resources/Private/JavaScript/DigitalcollectionsScripts.js
only small correction, two letters are twisted
> fix a small typo

- Classes/Controller/SingleCollectionController.php
- Classes/ViewHelpers/ProviderLogoCachedViewHelper.php
- Resources/Private/Plugins/Kitodo/Partials/TableOfContents/Children.html
- Resources/Private/Plugins/Kitodo/Partials/TableOfContents/Title.html
- Resources/Private/Plugins/Kitodo/Templates/Navigation/Main.html
- Resources/Private/Plugins/SingleCollection/Templates/Show.html
- composer.json
This PR is based on #43 and is companion to https://github.com/kitodo/kitodo-presentation/pull/840.
Before merging, the "(WIP) Allow dev-sxnd-fixes-search in Kitodo" commit should be reverted/removed.
> Adapt to Kitodo search performance PR

- Configuration/TypoScript/Plugin/Kitodo/setup.typoscript
- Resources/Private/Plugins/Kitodo/Templates/Toolbox/Main.html
Fix for https://github.com/kitodo/kitodo-presentation/issues/987
> Use viewData to pass pid in SearchInDocument tool

- Classes/ViewHelpers/XpathViewHelper.php
Class Doc was renamed to AbstractDocument and function getDoc was renamed to getCurrentDocument
> Use getCurrentDocument function

- Resources/Private/Language/de.locallang_kitodo.xlf
- Resources/Private/Language/locallang_kitodo.xlf
these are not supported by DFG Strukturdatenset and have not been in use since 2023-12-19
> mets:div types: remove 2 entries

- Classes/Controller/SingleCollectionController.php
It was renamed in Kitodo.Presentation
> Call `findSolrByCollections` function

- Configuration/TypoScript/Plugin/Kitodo/setup.typoscript
Change to keep slub_digitalcollections compatible with kitodo.presentation: https://github.com/kitodo/kitodo-presentation/pull/1156
> Adjust configuration for fulltext container

- Resources/Private/Partials/KitodoPageView.html
Fix for https://github.com/slub/slub_digitalcollections/issues/73
> Remove special case for catalouge search

- Resources/Private/Plugins/Kitodo/Templates/Toolbox/Main.html
Changes: https://github.com/kitodo/kitodo-presentation/pull/1248
> Adjust Toolbox template to conform to changes made in Kitodo.Presentation

- Configuration/TypoScript/constants.typoscript
They should be configured after portal is ready
> [MAINTENANCE] Remove ids from constants TS

- Resources/Private/Plugins/Kitodo/Templates/Toolbox/Main.html
Related to https://github.com/kitodo/kitodo-presentation/pull/1372
> [BUGFIX] Fix passing page id from `ToolboxController`

- Resources/Private/Plugins/SingleCollection/Partials/Results.html
> [BUGFIX] Fix links on result page

- Resources/Private/Plugins/Kitodo/Templates/Toolbox/Main.html
- Updates the `modeldownloadtool` 
- Adds the `viewerselectiontool`
> [FEATURE] 3D viewer selection

- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Plugins/Kitodo/Templates/Toolbox/Main.html
Fixes bug of Kitodo.Presentation https://github.com/kitodo/kitodo-presentation/issues/1429 which becomes visible in the DFG-Viewer
> [BUGFIX] Improve score tool conditions

- Resources/Private/Plugins/Kitodo/Templates/Collection/List.html
> [BUGFIX] Fix template for displaying list of collections - 4.1

- Resources/Private/Plugins/Kitodo/Templates/Collection/List.html
> [BUGFIX] Fix template for displaying list of collections

- Configuration/TypoScript/Plugin/Kitodo/common.typoscript
- Configuration/TypoScript/Plugin/Kitodo/setup.typoscript
- Configuration/TypoScript/Plugin/singleCollection.typoscript
- Configuration/TypoScript/SitePackage/navigation.typoscript
- Configuration/TypoScript/SitePackage/setup.typoscript
- Configuration/TypoScript/constants.typoscript
- Configuration/TypoScript/setup.typoscript
> [MAINTENANCE] Insert correct TS constants

- Configuration/TypoScript/Plugin/Kitodo/common.typoscript
- Configuration/TypoScript/Plugin/Kitodo/setup.typoscript
- Configuration/TypoScript/Plugin/singleCollection.typoscript
- Configuration/TypoScript/SitePackage/navigation.typoscript
- Configuration/TypoScript/SitePackage/setup.typoscript
- Configuration/TypoScript/constants.typoscript
- Configuration/TypoScript/setup.typoscript
> [BUGFIX] Insert `solrcore` to general plugin settings

- Resources/Private/Plugins/Kitodo/Templates/Navigation/Main.html
PR to fix https://github.com/kitodo/kitodo-presentation/issues/1489
There are also changes in kitodo-presentation and dfg-viewer.
> [BUGFIX] Move fullscreen to new section

- .github/phpstan.neon
Remove errors which are not appearing anymore
> [MAINTENANCE] Adjust PHPStan config
